apiVersion: apps/v1
kind: Deployment
metadata:
  name: syu-clubs
spec:
  replicas: 1
  selector:
    matchLabels:
        app: syu-clubs
  template:
    metadata:
      labels:
        app: syu-clubs
    spec:
      volumes:
      - name: django-nginx
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: syuclub
      containers:
      - name: syu-clubs2
        image: hongpark/syu-clubs2:latest
        ports:
        - containerPort: 8000
        # env:
        # - name: DJANGO_SETTINGS_MODULE
        #   value: "api.settings.prod"
        command: ["/bin/sh"]
        args: ["-c", "yes", "|","django", "manage.py", "collectstatic"]
        volumeMounts:
        - name: django-nginx
          mountPath: /app/static
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: django-nginx
          mountPath: /app/static
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
