version: '3'

services:
    app:
        container_name: syu_clubs
        # image: hongpark/syu-clubs:latest
        build:
            dockerfile: ./Dockerfile
        expose:
            # 이거랑
            - 8000
        ports:
            - "8080:8000"
        environment: 
            - DJANGO_SETTINGS_MODULE=api.settings.prod
        command:
            - bash
            - -c
            - |
                echo yes | python manage.py collectstatic
                python manage.py migrate
                gunicorn api.wsgi:application --bind=0.0.0.0:8000

    nginx:
        image: nginx:latest
        ports:
            # 이거 차이 
            - "8000:80"
        volumes:
            - .:/app
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - syu_clubs


