---
apiVersion: v1
kind: Service
metadata:
  name: syu-svc
  labels:
    app: syu-svc
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: syu-clubs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syu-clubs
spec:
  # replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
        app: syu-clubs
  template:
    metadata:
      labels:
        app: syu-clubs
    spec:
      volumes:
      - name: django-nginx
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: syuclub
      containers:
      - name: syu-clubs2
        image: hongpark/syu-clubs2:1.2.7
        imagePullPolicy: Always
        resources:
          requests:
            cpu: '0.5'
        # ports:
        # - containerPort: 8000
        # env:
        # - name: DJANGO_SETTINGS_MODULE
        #   value: "api.settings.prod"
        command: ["/bin/sh"]
        args: ["-c", "echo yes | python manage.py collectstatic && gunicorn api.wsgi:application --bind=0.0.0.0:8000;"]
        volumeMounts:
        - name: django-nginx
          mountPath: /app/static
      - name: nginx
        image: nginx:latest
        resources:
            requests:
              cpu: '0.5'
        ports:
        - containerPort: 80
        volumeMounts:
        - name: django-nginx
          mountPath: /app/static
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: syu-hpa
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: syu-clubs
  targetCPUUtilizationPercentage: 30
