# Generated by Django 3.1 on 2020-08-12 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_auto_20200811_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAdditionalInfo',
            fields=[
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auth.user')),
                ('profile', models.ImageField(upload_to='profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verfied', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users_additional_info',
            },
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'managed': False},
        ),
    ]
