# Generated by Django 3.1 on 2020-11-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200910_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postslike',
            options={},
        ),
    ]
