# Generated by Django 3.1 on 2020-08-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200812_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersadditionalinfo',
            name='profile',
            field=models.CharField(max_length=5000),
        ),
    ]
